// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLoqvHLAPffetNawyQuGSu3MGQ0ZTxmuA',
    appId: '1:847993627027:web:8f189897284f06664f0866',
    messagingSenderId: '847993627027',
    projectId: 'wall-92757',
    authDomain: 'wall-92757.firebaseapp.com',
    storageBucket: 'wall-92757.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdxMg4kLTNvMunBko3DCZ3JiO_z9ogUr0',
    appId: '1:847993627027:android:7d838cc214831c694f0866',
    messagingSenderId: '847993627027',
    projectId: 'wall-92757',
    storageBucket: 'wall-92757.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE9AgpOnWZ99B3bMra0VsPJveVT_k5LFc',
    appId: '1:847993627027:ios:94e756f7023194dc4f0866',
    messagingSenderId: '847993627027',
    projectId: 'wall-92757',
    storageBucket: 'wall-92757.firebasestorage.app',
    iosBundleId: 'com.example.flutterWall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE9AgpOnWZ99B3bMra0VsPJveVT_k5LFc',
    appId: '1:847993627027:ios:94e756f7023194dc4f0866',
    messagingSenderId: '847993627027',
    projectId: 'wall-92757',
    storageBucket: 'wall-92757.firebasestorage.app',
    iosBundleId: 'com.example.flutterWall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLoqvHLAPffetNawyQuGSu3MGQ0ZTxmuA',
    appId: '1:847993627027:web:13f6ea7ae74284ea4f0866',
    messagingSenderId: '847993627027',
    projectId: 'wall-92757',
    authDomain: 'wall-92757.firebaseapp.com',
    storageBucket: 'wall-92757.firebasestorage.app',
  );

}